version: '3'
services:
  web:
    build: ./
    ports:
      - "81:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./local/php.ini:/usr/local/etc/php/php.ini
    networks:
      - my_symfony_network


  db:
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_symfony_db
      MYSQL_USER: yassine
      MYSQL_PASSWORD: 123456
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - my_symfony_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - my_symfony_network


networks:
  my_symfony_network:
    driver: bridge
